[12.0] REST Refactor
sodexis/avatax_connector pull request #49
Opened 2020-05-19 14:03 UTC by dreispt

Depends on #45
Changes the way taxes are computed, but only when using the REST API.

2020-09-22 12:41 UTC, dreispt commented
@atchuthan I now feel that this is mature enough to merge.
I worry that the legacy  SOAP API mode is unaffected and continues working as before., but I would like independent confirmation.
It would be nice if you could test this, and give a green light for the merge.
Thanks!

2020-10-07 14:12 UTC, atchuthan commented
@dreispt we are testing it

2020-10-07 16:30 UTC, dreispt commented
@atchuthan Thank you. Remember to also confirm that it still works an before, when choosing SOAP mode.

2020-10-27 12:18 UTC, dreispt commented
@atchuthan I did more tests on my end, and the SOAP mode seems to be working properly.
I'm merging, please take extra care if upgrading any of your current customers.
In case a rollback is needed, the previous commit to checkout from is 1c0dfa6.

2020-10-28 12:28 UTC, atchuthan requested changes

2020-10-28 12:28 UTC, atchuthan commented on avatax_connector/models/sale_order.py
> +    @api.depends("order_line.price_total", "order_line.tax_amt")
If we remove the tax selected in SO line and save it, the Taxes is not set to 0.  So, we could add Taxes field(tax_id) in SO line to depends.

2020-10-28 12:30 UTC, atchuthan commented
Also, we could add fiscal position, to set the initial tax in SO line with AVATAX record like we did it for v13(https://github.com/OCA/account-fiscal-rule/blob/13.0/account_avatax/data/avalara_salestax_data.xml)

2020-10-28 12:42 UTC, dreispt commented on avatax_connector/models/sale_order.py
> +    @api.depends("order_line.price_total", "order_line.tax_amt")
OK, let me check that

2020-10-28 12:44 UTC, dreispt commented
> Also, we could add fiscal position, to set the initial tax in SO line with AVATAX record like we did it for v13(https://github.com/OCA/account-fiscal-rule/blob/13.0/account_avatax/data/avalara_salestax_data.xml)

This is a significant usage change and I worry that it could cause issues on companies currently using the connector.
It would be best done in a separate PR, if you think it is important and can be done safely.

2020-10-30 08:27 UTC, atchuthan commented
Okay, we will create a new PR for fiscal position changes in the future

2020-10-30 12:16 UTC, dreispt commented on avatax_connector/models/sale_order.py
> +    @api.depends("order_line.price_total", "order_line.tax_amt")
Added

2021-04-14 13:20 UTC, dreispt commented
@atchuthan Can we merge this?
I've been maintaining the refactor fork branch for a while, and that doesn't make much sense.

2021-04-19 07:32 UTC, atchuthan commented
We are testing it once again with the latest v12 base code

2021-04-20 10:44 UTC, atchuthan approved these changes

2021-04-20 10:46 UTC, merged

2021-04-20 11:19 UTC, dreispt commented
🎉